---
apiVersion: v1
kind: Service
metadata:
  name: app-lb
  namespace: k8s-probe-spring
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 31000
  selector:
    role: app
